.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. ilcoin_qt test_ilcoin_qt
clean: FORCE
	$(MAKE) -C .. ilcoin_qt_clean test_ilcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_ilcoin_qt_check
ilcoin-qt ilcoin-qt.exe: FORCE
	 $(MAKE) -C .. ilcoin_qt
